Minio Client Extension to Support Flexible Endpoint, Port, and TLS Configurations
quarkiverse/quarkus-minio pull request #306
Opened 2024-03-08 23:59 UTC by TartanLeGrand

This PR introduces targeted enhancements to the `quarkiverse-minio` extension, aimed at increasing its flexibility by allowing users to specify MinIO endpoints without requiring explicit "http://" or "https://" prefixes, configure custom port numbers, and toggle TLS security. By default, the extension now assumes port 443 for connections and enables TLS, aligning with common MinIO deployment practices. These changes facilitate easier integration with MinIO services, accommodating a variety of network and security configurations.

#### Changes

1. **Simplified Endpoint Configuration**: Updated `MinioRuntimeConfiguration` to gracefully handle MinIO server URLs without the need for "http://" or "https://" prefixes, simplifying configuration files.
2. **Custom Port and TLS Toggle**: Introduced optional configurations for custom port numbers and a TLS toggle. This enhancement allows developers to easily switch between standard and custom ports and choose between secure (TLS) and non-secure connections based on their deployment requirements.
3. **Default Settings for Port and TLS**: Set default values for the port (443) and TLS (enabled) to ensure out-of-the-box security and compatibility with standard MinIO server deployments.

#### Motivation

The primary motivation for these updates is to provide Quarkus developers with a more adaptable and user-friendly way to configure MinIO client connections, catering to the diverse setups found in real-world applications. These enhancements are a step towards supporting the comprehensive set of use cases documented in the MinIO Java Client API, making the extension more versatile.

#### Next Steps

While this PR addresses specific aspects of MinIO client configuration, future enhancements should aim to support the full spectrum of use cases outlined in the [MinIO Java Client API documentation](https://min.io/docs/minio/linux/developers/java/API.html). This includes anonymous access, authenticated access with different security mechanisms, region specification, and the use of custom HTTP clients. Planning and implementing these features will further solidify the `quarkiverse-minio` extension as a robust and comprehensive solution for MinIO integration in Quarkus applications.

#### How to Test

1. Configure your `application.properties` to connect to a MinIO server, specifying the endpoint without the "http://" or "https://" prefix, and adjust the port and TLS settings as needed.
2. Deploy your Quarkus application and ensure it can successfully communicate with the specified MinIO server.

#### Documentation

The documentation has been updated to reflect these new configuration options, offering guidance on how to leverage the simplified endpoint configuration, custom port numbers, and TLS settings.

2024-03-11 11:41 UTC, TartanLeGrand commented
@jtama 👋

2024-03-13 07:26 UTC, jtama commented
Ok so if we follow that path what happens if someone specifies an url as "http://" and also specifies to use tls or vice/versa.

Any how I would be happy to accept the PR but we need to make sure we don't broke existing configurations, we need to update the devservice and documentation to refelct the changes.

2024-03-13 07:27 UTC, jtama requested changes
Ok so if we follow that path what happens if someone specifies an url as "http://" and also specifies to use tls or vice/versa.

Any how I would be happy to accept the PR but we need to make sure we don't broke existing configurations, we need to update the devservice and documentation to refelct the changes.

2024-03-13 07:53 UTC, TartanLeGrand commented
It's not a breaking change, because the builder make an `HttpUtils.getBaseUrl(endpoint);`.

2024-03-13 08:18 UTC, jtama commented
OK, but the test and devservices still have to be impacted as well as the documentation.

2024-03-14 08:25 UTC, TartanLeGrand commented
Hello @jtama 👋, I have made some changes can you relaunch the pipe ?

Why you dont let the pipeline for every PR ? 🤔

2024-03-14 09:26 UTC, jtama commented
> Hello @jtama 👋, I have made some changes can you relaunch the pipe ?
> 
> Why you dont let the pipeline for every PR ? 🤔

It's the classical quarkiverse setup.

Sorry I don't have much time this week will have more next one.

In the doc could you clarify that the port can be assigned with the host directly or via the dedicated property ?

2024-03-27 10:36 UTC, jtama commented
Sorry I didn't saw you last push. They aren't enough though. It should be better with the following patch (I don't have write access to your fork) 

[port-tls.patch](https://github.com/quarkiverse/quarkus-minio/files/14771943/port-tls.patch)

2024-04-04 08:48 UTC, jtama commented
@TartanLeGrand  ?

2024-04-23 07:27 UTC, jtama commented
@TartanLeGrand Did you had a chance to check the patch ? 
https://github.com/quarkiverse/quarkus-minio/pull/306#issuecomment-2022433905

2024-05-29 06:46 UTC, closed without merging